[package]
name = "rift-atlas"
version = "2.1.9"
description = "Aplicacion de League of Legends basada en Data Dragon."
authors = ["BEF172"]
license = "MIT"
edition = "2021"

[lib]
name = "rift_atlas_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "devtools"] }
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.29"
tokio-native-tls = "0.3"
native-tls = "0.2"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream", "blocking"] }
uuid = { version = "1", features = ["v4"] }
sha2 = "0.10"
rand = "0.9"
zip = "4"
chrono = "0.4"
url = "2"
log = "0.4"
env_logger = "0.11"
base64 = "0.22"
open = "5"
hex = "0.4"
mime_guess = "2"
regex-lite = "0.1"
sevenz-rust2 = "0.21.0"
rust-ini = "0.21"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Console",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Registry",
    "Win32_UI_WindowsAndMessaging",
] }
