const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("riftAtlas", {
  appName: "Rift Atlas",
  hasRiotApiKey: () => ipcRenderer.invoke("riot:has-api-key"),
  setRiotApiKey: (apiKey) => ipcRenderer.invoke("riot:set-api-key", apiKey),
  clearRiotApiKey: () => ipcRenderer.invoke("riot:clear-api-key"),
  lookupPlayer: (payload) => ipcRenderer.invoke("riot:lookup-player", payload),
  getChampionData: () => ipcRenderer.invoke("data:get-champions"),
  getTierLane: (payload) => ipcRenderer.invoke("tiers:get-lane", payload),
  getChampionBuild: (payload) => ipcRenderer.invoke("builds:get-champion", payload),
  openExternal: (url) => ipcRenderer.invoke("app:open-external", url),
  checkUpdates: () => ipcRenderer.invoke("app:check-updates"),
  getUserDataPath: () => ipcRenderer.invoke("app:get-user-data-path"),
  openUserDataPath: () => ipcRenderer.invoke("app:open-user-data-path"),
  getEngineDllStatus: () => ipcRenderer.invoke("app:get-engine-dll-status"),
  openEngineFolder: () => ipcRenderer.invoke("app:open-engine-folder"),
  selectModFolder: () => ipcRenderer.invoke("mods:select-folder"),
  selectCustomModFiles: () => ipcRenderer.invoke("mods:select-custom-mod-files"),
  selectCustomModFolder: () => ipcRenderer.invoke("mods:select-custom-mod-folder"),
  revealModPath: (filePath) => ipcRenderer.invoke("mods:reveal-path", filePath),
  selectLeagueGame: () => ipcRenderer.invoke("mods:select-league-game"),
  selectSkinLibrary: () => ipcRenderer.invoke("mods:select-skin-library"),
  indexSkinLibrary: (folderPath) => ipcRenderer.invoke("mods:index-skin-library", folderPath),
  downloadLeagueSkins: () => ipcRenderer.invoke("mods:download-league-skins"),
  getDownloadedLeagueSkinsPath: () => ipcRenderer.invoke("mods:get-downloaded-league-skins-path"),
  indexDownloadedLeagueSkins: () => ipcRenderer.invoke("mods:index-downloaded-league-skins"),
  selectLtk: () => ipcRenderer.invoke("mods:select-ltk"),
  openLtk: (executablePath) => ipcRenderer.invoke("mods:open-ltk", executablePath),
  stopOverlay: () => ipcRenderer.invoke("mods:stop-overlay"),
  overlayStatus: () => ipcRenderer.invoke("mods:overlay-status"),
  diagnoseOverlay: (payload) => ipcRenderer.invoke("mods:diagnose-overlay", payload),
  getLtkStatus: (payload) => ipcRenderer.invoke("ltk:get-status", payload),
  importLtkMods: (payload) => ipcRenderer.invoke("ltk:import-mods", payload),
  detectLtk: () => ipcRenderer.invoke("ltk:detect"),
  downloadAndInstallLtk: () => ipcRenderer.invoke("ltk:download-and-install"),
  selectBocchiSidecar: () => ipcRenderer.invoke("mods:select-bocchi-sidecar"),
  selectBocchiDll: () => ipcRenderer.invoke("mods:select-bocchi-dll"),
  autoConfigureOverlay: (payload) => ipcRenderer.invoke("mods:auto-configure-overlay", payload),
  downloadCslolTools: (payload) => ipcRenderer.invoke("mods:download-cslol-tools", payload),
  onDownloadProgress: (handler) => ipcRenderer.on("download-progress", (_event, payload) => handler(payload)),
  getPartyFileInfo: (filePath) => ipcRenderer.invoke("party:get-file-info", filePath),
  readPartyFileChunk: (payload) => ipcRenderer.invoke("party:read-file-chunk", payload),
  writePartyFile: (payload) => ipcRenderer.invoke("party:write-file", payload),
  clearPartyP2PFiles: () => ipcRenderer.invoke("party:clear-p2p-files"),
  runBocchiOverlay: (payload) => ipcRenderer.invoke("mods:run-bocchi-overlay", payload)
});
